In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\aacjp\Downloads\Top50.csv', engine='python')
df

Unnamed: 0                                         Track.Name  \
0            1                                           Señorita   
1            2                                              China   
2            3                      boyfriend (with Social House)   
3            4                    Beautiful People (feat. Khalid)   
4            5                        Goodbyes (Feat. Young Thug)   
5            6                  I Don't Care (with Justin Bieber)   
6            7                                             Ransom   
7            8                                  How Do You Sleep?   
8            9                              Old Town Road - Remix   
9           10                                            bad guy   
10          11                                           Callaita   
11          12              Loco Contigo (feat. J. Balvin & Tyga)   
12          13                                  Someone You Loved   
13          14                                 Otro Trago - Remix   
14          15           Money In The Grave (Drake ft. Rick Ross)   
15          16                          No Guidance (feat. Drake)   
16          17                                         LA CANCIÓN   
17          18      Sunflower - Spider-Man: Into the Spider-Verse   
18          19                                             Lalala   
19          20                                        Truth Hurts   
20          21                                Piece Of Your Heart   
21          22                                             Panini   
22          23                               No Me Conoce - Remix   
23          24                                    Soltera - Remix   
24          25                       bad guy (with Justin Bieber)   
25          26                                If I Can't Have You   
26          27                                       Dance Monkey   
27          28                                           It's You   
28          29                                          Con Calma   
29          30                                      QUE PRETENDES   
30          31                                           Takeaway   
31          32                                            7 rings   
32          33                                  0.958333333333333   
33          34          The London (feat. J. Cole & Travis Scott)   
34          35                                  Never Really Over   
35          36  Summer Days (feat. Macklemore & Patrick Stump ...   
36          37                                         Otro Trago   
37          38                     Antisocial (with Travis Scott)   
38          39                                             Sucker   
39          40  fuck, i'm lonely (with Anne-Marie) - from “13 ...   
40          41                                        Higher Love   
41          42                              You Need To Calm Down   
42          43                                            Shallow   
43          44                                               Talk   
44          45                                         Con Altura   
45          46                                    One Thing Right   
46          47                                          Te Robaré   
47          48                                            Happier   
48          49                                      Call You Mine   
49          50      Cross Me (feat. Chance the Rapper & PnB Rock)   

         Artist.Name             Genre  Beats.Per.Minute  Energy  \
0       Shawn Mendes      canadian pop               117      55   
1           Anuel AA    reggaeton flow               105      81   
2      Ariana Grande         dance pop               190      80   
3         Ed Sheeran               pop                93      65   
4        Post Malone           dfw rap               150      65   
5         Ed Sheeran               pop               102      68   
6       

In [2]:
T = df.drop(['Unnamed: 0','Track.Name', 'Artist.Name'], axis='columns')
T.head()

Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
0    canadian pop               117      55            76              -6   
1  reggaeton flow               105      81            79              -4   
2       dance pop               190      80            40              -4   
3             pop                93      65            64              -8   
4         dfw rap               150      65            58              -4   

   Liveness  Valence.  Length.  Acousticness..  Speechiness.  Popularity  
0         8        75      191               4             3          79  
1         8        61      302               8             9          92  
2        16        70      186              12            46          85  
3         8        55      198              12            19          86  
4        11        18      175              45             7          94

In [3]:
dummies = pd.get_dummies(T.Genre)
dummies.head(5)

atl hip hop  australian pop  big room  boy band  brostep  canadian hip hop  \
0            0               0         0         0        0                 0   
1            0               0         0         0        0                 0   
2            0               0         0         0        0                 0   
3            0               0         0         0        0                 0   
4            0               0         0         0        0                 0   

   canadian pop  country rap  dance pop  dfw rap  ...  electropop  \
0             1            0          0        0  ...           0   
1             0            0          0        0  ...           0   
2             0            0          1        0  ...           0   
3             0            0          0        0  ...           0   
4             0            0          0        1  ...           0   

   escape room  latin  panamanian pop  pop  pop house  r&b en espanol  \
0            0      0               0    0          0               0   
1            0      0               0    0          0               0   
2            0      0               0    0          0               0   
3            0      0               0    1          0               0   
4            0      0               0    0          0               0   

   reggaeton  reggaeton flow  trap music  
0          0               0           0  
1          0               1           0  
2          0               0           0  
3          0               0           0  
4          0               0           0  

[5 rows x 21 columns]

In [4]:
merged = pd.concat([T,dummies],axis='columns')
merged.head(5)

Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
0    canadian pop               117      55            76              -6   
1  reggaeton flow               105      81            79              -4   
2       dance pop               190      80            40              -4   
3             pop                93      65            64              -8   
4         dfw rap               150      65            58              -4   

   Liveness  Valence.  Length.  Acousticness..  Speechiness.  ...  electropop  \
0         8        75      191               4             3  ...           0   
1         8        61      302               8             9  ...           0   
2        16        70      186              12            46  ...           0   
3         8        55      198              12            19  ...           0   
4        11        18      175              45             7  ...           0   

   escape room  latin  panamanian pop  pop  pop house  r&b en espanol  \
0            0      0               0    0          0               0   
1            0      0               0    0          0               0   
2            0      0               0    0          0               0   
3            0      0               0    1          0               0   
4            0      0               0    0          0               0   

   reggaeton  reggaeton flow  trap music  
0          0               0           0  
1          0               1           0  
2          0               0           0  
3          0               0           0  
4          0               0           0  

[5 rows x 32 columns]

In [5]:
final = merged.drop(['Genre','pop'],axis='columns')
final.head(5)

Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  Popularity  ...  edm  electropop  \
0      191               4             3          79  ...    0           0   
1      302               8             9          92  ...    0           0   
2      186              12            46          85  ...    0           0   
3      198              12            19          86  ...    0           0   
4      175              45             7          94  ...    0           0   

   escape room  latin  panamanian pop  pop house  r&b en espanol  reggaeton  \
0            0      0               0          0               0          0   
1            0      0               0          0               0          0   
2            0      0               0          0               0          0   
3            0      0               0          0               0          0   
4            0      0               0          0               0          0   

   reggaeton flow  trap music  
0               0           0  
1               1           0  
2               0           0  
3               0           0  
4               0           0  

[5 rows x 30 columns]

In [6]:
X = final.drop(['Popularity'],axis='columns')
X.head(5)

Beats.Per.Minute  Energy  Danceability  Loudness..dB..  Liveness  Valence.  \
0               117      55            76              -6         8        75   
1               105      81            79              -4         8        61   
2               190      80            40              -4        16        70   
3                93      65            64              -8         8        55   
4               150      65            58              -4        11        18   

   Length.  Acousticness..  Speechiness.  atl hip hop  ...  edm  electropop  \
0      191               4             3            0  ...    0           0   
1      302               8             9            0  ...    0           0   
2      186              12            46            0  ...    0           0   
3      198              12            19            0  ...    0           0   
4      175              45             7            0  ...    0           0   

   escape room  latin  panamanian pop  pop house  r&b en espanol  reggaeton  \
0            0      0               0          0               0          0   
1            0      0               0          0               0          0   
2            0      0               0          0               0          0   
3            0      0               0          0               0          0   
4            0      0               0          0               0          0   

   reggaeton flow  trap music  
0               0           0  
1               1           0  
2               0           0  
3               0           0  
4               0           0  

[5 rows x 29 columns]

In [7]:
y = final.Popularity
y.head(5)

0    79
1    92
2    85
3    86
4    94
Name: Popularity, dtype: int64

In [13]:
from sklearn.linear_model import LinearRegression
import numpy as np
reg = LinearRegression()
reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.coef_

array([ 6.90354183e-03,  4.69790274e-02, -3.04335821e-02, -4.18324814e-01,
        6.94253513e-02, -7.01080174e-02, -3.93295883e-02, -2.23941557e-02,
       -5.42824561e-02,  7.00058579e-01, -1.02169554e+00, -1.08120950e+00,
       -3.92925345e+00,  1.24243734e+00,  2.80389564e+00, -9.57808091e+00,
        1.01036683e+00, -1.60165645e-01,  6.72331856e+00, -1.15514901e+00,
        6.76932709e+00,  4.17916803e+00,  6.00210388e+00,  7.68639204e+00,
        2.56699917e+00,  4.45148324e+00,  6.51393118e+00,  6.65776025e+00,
        1.97853490e+00])

In [16]:
reg.predict([[150, 65, 58, -4, 11, 18, 175, 45, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#Goodbyes

array([95.39438265])

In [17]:
reg.predict([[130, 69, 81, -4, 6, 47, 163, 3, 11, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#Exotic

array([87.53611606])

In [18]:
reg.predict([[140, 50, 74, -10, 12, 47, 192, 1, 29, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#Im Straight

array([87.77923207])

In [20]:
from sklearn.metrics import mean_absolute_error
y_true = [94]
y_pred = [95.39438265]
mean_absolute_error(y_true, y_pred)

1.3943826499999972